spring:
  application:
    name: payment_service
  datasource:
    url: jdbc:h2:./db/payment_service;AUTO_SERVER=TRUE
    username: root
    password: qwerty
    driver-class-name: org.h2.Driver
  #  sql:
  #    init:
  #      mode: always

  liquibase:
    change-log: classpath:/db/changelog/master.yaml

server:
  port: 8080
